apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: {{ .Values.name }}
    type: image
  name: {{ .Values.name }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.image.name }}:{{ .Values.image.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: {{ .Values.git.contextDir }}
    git:
      ref: {{ .Values.git.ref }}
      uri: {{ .Values.git.uri }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: "{{ .Values.builder.image }}:{{ .Values.builder.tag }}"
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
