apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  {{ if .Values.host }}host: {{ .Values.host }}{{ end }}
  wildcardPolicy: None
