apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.secretName }}"
type: Opaque
stringData:
  WEBHOOK_TOKEN: "{{ .Values.config.webhookToken }}"
  CLEANUP_TOKEN: "{{ .Values.config.cleanupToken }}"
  HANGOUTS_SPACE: "{{ .Values.config.hangoutsSpace }}"
  CLIENT_ID: "{{ .Values.config.clientId }}"
  CLIENT_SECRET: "{{ .Values.config.clientSecret }}"
  SSO_URL: "{{ .Values.config.ssoUrl }}"
  BACKEND_URL: "{{ .Values.config.backendUrl }}"
  CHAT_WEBHOOK_URL: {{ .Values.config.chatWebhookUrl }}
  GITHUB_SECRET: {{ .Values.config.githubSecret }}
  USER_MAP_JSON: {{ .Values.config.userMapJson }}
