apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.secretName }}"
type: Opaque
stringData:
  WEBHOOK_TOKEN: "{{ .Values.config.webhookToken }}"
  HANGOUTS_SPACE: "{{ .Values.config.hangoutsSpace }}"
